schema-version: v1
kind: plugin
metadata:
  name: my-first-plugin
  display-name: my-first-plugin
  description: Demo Teste Plugin
  version: 0.0.16
  picture: plugin.png
spec:
  type: app
  compatibility:
    - python
  about: docs/about.md
  implementation: docs/implementation.md
  release-notes: docs/release-notes-0.0.1.md
  requirements: docs/requirements.md
  technologies: # Ref: https://docs.stackspot.com/content-creator/studio/yaml-files/plugin-yaml/#technologies
    - Api
  repository: https://github.com/natane-goncalves/demoStackspot/my-first-plugin
  inputs:
    - label: Project name
      name: project_name
      type: text
      global: true
  hooks:
    - type: run-script
      trigger: after-render
      script: main.py
