schema-version: v1
kind: plugin
metadata:
  name: my-first-plugin
  display-name: my-first-plugin
  description: Demo Teste Plugin
  version: 0.0.4
  picture: plugin.png
spec:
  type: app
  compatibility:
    - python
  about: docs/about.md
  implementation: docs/implementation.md
  release-notes: docs/release-notes-0.0.1.md
  requirements: docs/requirements.md
  technologies: # Ref: https://docs.stackspot.com/content-creator/studio/yaml-files/plugin-yaml/#technologies
    - Api
  inputs:
    - label: Project name
      name: project_name
      type: text
      global: true
  python:
    workdir: .
    script: main.py
